### ISSUE TITLE
Should this work? 

### ISSUE THREAD

**Issue by wayne-o** [waterlock/waterlock-facebook-auth#2]
Can anyone have a ganders at this and tell me if I'm right or doing something wrong? 

http://stackoverflow.com/q/27877641/156888

**Comment by wayne-o** [comment]
As an update here is a new Q:

http://stackoverflow.com/questions/27890654/ember-simple-auth-and-torii

Basically - torii authenticates the client and I get the auth code. From within torii's callback I am sending a request to api/auth/facebook_oauth2?code={{some-auth-code-from-FB}}

But I always get the error telling me the authcode is not valid...

Am I doing this right? Is there another code I should be sending to that URL?

**Comment by wayne-o** [comment]
I have figured that there is no /access_token endpoint for the client to send an access_token to to allow the api to auth that way (IOW using this workflow https://developers.facebook.com/docs/facebook-login/access-tokens?locale=en_GB#authClientServer) I am creating a PR that takes care of this - just wondering if there was a reason it wasn't included initially? i.e. am I wasting my time because i don't fully understand how this stuff works or would this be useful?

**Comment by davidrivera** [comment]
Hey thanks! Yea this module was a WIP i simply implemented the most basic oauth structure to allow facebook to authenticate. Sorry i've been busy lately, any pr you send would be much appreciated! :+1:

**Comment by wayne-o** [comment]
I've jigged some things about and moved it to master - hope that's ok. How can we get this stuff pushed to NPM?

Also - I seem to be reaping havoc on your coverage - I'll take a stab at fixing that over the weekend
