### ISSUE TITLE
facebookId attribute too long for waterline integer

### ISSUE THREAD

**Issue by lhdo** [waterlock/waterlock-facebook-auth#5]
Hi, 

I've been testing the waterlock facebook module and ran into some issues. This is not necessarily a problem with waterlock-facebook-auth. 

The 17 digit facebookId is longer than the default allowed for type=integer using the waterline ORM (for mysql). The result is an incorrect store of the facebookId upon creation of a new user. The initial login and authentication is successful and an entry is created in the Auth table. However, upon logging out and logging back in, the authentication fails because the facebookId is not the correct 17 digit value (truncated as int(11) in mysql). 

When using a local disk based storage, the full 17 digit facebookId is stored correctly and the problem does not occur. This is why testing on a default sails install does not reveal the issue. I have not tested on any other databases except mysql, but I suspect that a lack of support for larger integer types will be a problem as well.

My solution was to either: 
1) manually change the facebookId to bigint unsigned unique (20) 
OR
2) change the auth attribute facebookId to type string -- varchar(255) unique in mysql.

For development purposes, I chose option 2 since we are constantly changing our models and need to drop the tables. I don't see any checks for int type or mathematical operations on the facebookId so this seems to work. 

Performance differences between an int and varchar/char (unique and indexed) seems to be negligible even on millions of records so perhaps changing the facebookId attribute type to string for the facebook-auth module is the best way forward.

**Comment by shamilus** [comment]
Same for postgres

**Comment by wayne-o** [comment]
This is now float but we are waiting on a release. I'm going to close this now - hopefuly there will be a release out soon in the mean time you can install this package from master using the git+https syntax.
