### ISSUE TITLE
pluralizeEndpoints does not work

### ISSUE THREAD

**Issue by mxrguspxrt** [waterlock/waterlock-facebook-auth#7]
redirect_to=HOST/auth/

should be
redirect_to=HOST/auths/

**Comment by DiknT** [comment]
this has already been fixed in master by commit 3e5a6afb97d30e792436ba9f2d1c9f4cb4fecacf but needs a new release to be pushed

**Comment by wayne-o** [comment]
Closing as fixed in https://github.com/waterlock/waterlock-facebook-auth/commit/3e5a6afb97d30e792436ba9f2d1c9f4cb4fecacf
